name: Call Python Reusable Workflow

on:
  workflow_dispatch:
  push:

jobs:
  call-python-workflow:
    strategy:
    matrix:
     build-tool: ["pip","uv","pipenv","poetry"]
    uses: 
    with: ./.github/workflows/python-reusable-workflow.yml
      python-version: "3.9"
      build-tool: $ {{ matrix.build-tool }}
