name: Call Python Reusable Workflow

on:
  workflow_dispatch:
  push:

jobs:
  call-python-workflow:
    uses: ./.github/workflows/python-reusable-workflow.yml
    with:
      python-version: "3.9"
      build-tool: "pipenv"
