name: Call Python Reusable Workflow

on:
  workflow_dispatch:
  push:

jobs:
  call-python-workflow:
    uses: ./.github/workflows/python-reusable-workflow.yml
    with:
      python-version: "3.11"
      build-tool: "poetry"
    # ✅ Add `runs-on` here
    runs-on: ubuntu-latest
